apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-apjung-admin-cicd-agent-deploy
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins-apjung-admin-cicd-agent
    app.kubernetes.io/instance: jenkins-apjung-admin-cicd-agent-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jenkins-apjung-admin-cicd-agent-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-apjung-admin-cicd-agent-agent
        app.kubernetes.io/instance: jenkins-apjung-admin-cicd-agent-pod
    spec:
      securityContext:
        fsGroup: 412
      containers:
        - name: jenkins-apjung-admin-cicd-agent-pod
          image: jenkins/inbound-agent:latest-jdk11
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          env:
            - name: JENKINS_JAVA_OPTIONS
              value: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
            - name: JENKINS_URL
              value: "http://jenkins-master-svc"
            - name: JENKINS_AGENT_NAME
              value: "apjung-admin-cicd-agent"
          envFrom:
            - secretRef:
                name: jenkins-apjung-admin-cicd-agent.secret
          command:
            - 'chmod'
            - '-R'
            - '777'
            - '/var/run/docker.sock'
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-socket
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
