apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-master-pv
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins-master
    app.kubernetes.io/instance: jenkins-master-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /storage/pv/jenkins

