apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube-extensions
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      storage: sonarqube-extensions

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube-data
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      storage: sonarqube-data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube-conf
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      storage: sonarqube-conf
