apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-resource
  namespace: prod
spec:
  hard:
    requests:
      cpu: "250m"
      memory: "256Mib"
    limits:
      cpu: "250m"
      memory: "256Mib"
