apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-apjung-dev-agent-volume
  namespace: jenkins
  labels:
    storage: jenkins-apjung-dev-agent-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    path: /storage/pv/jenkins-apjung-dev
    server: 192.168.219.210

