apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-apjung-dev-agent
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      storage: jenkins-apjung-dev-agent-volume
