apiVersion: apps/v1
kind: Deployment
metadata:
  name: apjung-backend-dev-deploy
  namespace: dev
  labels:
    app.kubernetes.io/name: apjung-backend-dev
    app.kubernetes.io/instance: apjung-backend-dev-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: apjung-backend-dev-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apjung-backend-dev
        app.kubernetes.io/instance: apjung-backend-dev-pod
    spec:
      imagePullSecrets:
        - name: dockerhub-secrets
      containers:
        - name: apjung-backend-dev-pod
          image: labyu/apjung-backend:dev-98
          ports:
            - containerPort: 8080

          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: apjung-backend-dev.secret-db
            - secretRef:
                name: apjung-backend-dev.secret-jwt
            - secretRef:
                name: apjung-backend-dev.secret-smtp
            - secretRef:
                name: apjung-backend-aws.secret
