apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-apjung-backend-bracnh-test-agent-deploy
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins-apjung-backend-bracnh-test-agent
    app.kubernetes.io/instance: jenkins-apjung-backend-bracnh-test-agent-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: jenkins-apjung-backend-bracnh-test-agent-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins-apjung-backend-bracnh-test-agent
        app.kubernetes.io/instance: jenkins-apjung-backend-bracnh-test-agent-pod
    spec:
      containers:
        - name: jenkins-apjung-backend-bracnh-test-agent-pod
          image: jenkins/inbound-agent:latest-jdk11
          ports:
            - containerPort: 8080
            - containerPort: 50000
          resources:
            requests:
              memory: "800Mib"
              cpu: "250m"
            limits:
              memory: "800Mib"
              cpu: "250m"
          env:
            - name: JENKINS_JAVA_OPTIONS
              value: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
            - name: JENKINS_URL
              value: "http://jenkins-master-svc"
            - name: JENKINS_AGENT_NAME
              value: "apjung-backend-branch-test-agent"
          envFrom:
            - secretRef:
                name: jenkins-apjung-backend-branch-test-agent.secret
            - secretRef:
                name: apjung-backend-aws.secret
