apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-pv
  namespace: mysql
  labels:
  app.kubernetes.io/name: mysql-dev
  app.kubernetes.io/instance: mysql-dev-pv
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /storage/pv/mysql-dev

