apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dev-volume
  namespace: mysql
  labels:
    storage: mysql-dev
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /storage/pv/mysql-dev

