apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dev-pvc
  namespace: mysql
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      app.kubernetes.io/instance: mysql-dev-pv
