apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-dev
  namespace: mysql
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      storage: mysql-dev
